client:
  myid: BrainA
  client_listen_port: 0
  servers:
    - addr: localhost
      port: 8008

peerserver:
  myid: BotServer-P-Debug
  peer_server_listen_port: 0
  client_listen_port: 8008
  peer_servers:
    - addr: '0'
      port: 0
  clients:
    - addr: '0'
      port: 0

